export const EDIT_RECIPE_CRITERIA = 'EDIT_RECIPE_CRITERIA';

export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const ADD_INGREDIENT_DETAILS = 'ADD_INGREDIENT_DETAILS';
export const EDIT_INGREDIENT_DETAILS = 'EDIT_INGREDIENT_DETAILS';
export const REMOVE_INGREDIENT_DETAILS = 'REMOVE_INGREDIENT_DETAILS';
export const CLEAR_ALERT_INGREDIENT = 'CLEAR_ALERT_INGREDIENT';

export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';